name: Compress images
on:
  pull_request:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'

jobs:
  build:
    name: Compress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2.3.4
        with:
          ref: main
      - name: Compress Images
        uses: calibreapp/image-actions@main
        id: calibre
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: ${{ github.event_name != 'pull_request' }}
      - name: Create Pull Request
        if: |
          github.event_name != 'pull_request' &&
          steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Auto Compress Images
          branch-suffix: timestamp
          commit-message: Compress Images
          labels: auto_merge
          body: ${{ steps.calibre.outputs.markdown }}